apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-amf-config
  labels:
    epc-mode: amf
data:
  amf.yaml: |
    global:
    max:
      ue: 1024
    logger:
     file:
       path: /var/log/open5gs/amf.log
        #level: debug
        #domain: sbi
    amf:
        sbi:
          server:
          - address: 0.0.0.0
            advertise: amf-svc
          client:
           scp:
           - uri: http://scp-svc   
        ngap:
          server:
          - dev: eth0
        metrics:
          server:
          - dev: eth0
            port: 9091
        guami:
          - plmn_id:
              mcc: {{ .Values.mcc }}
              mnc: {{ .Values.mnc }}
            amf_id:
              region: 2
              set: 1
        tai:
          - plmn_id:
              mcc: {{ .Values.mcc }}
              mnc: {{ .Values.mnc }}
            tac: {{ .Values.tac }}
        plmn_support:
        - plmn_id:
            mcc: {{ .Values.mcc }}
            mnc: {{ .Values.mnc }}          
          s_nssai:
          - sst: {{ .Values.sst }}
            sd: {{ .Values.sd }}
        security:
            integrity_order : [ NIA2, NIA1, NIA0 ]
            ciphering_order : [ NEA0, NEA1, NEA2 ]
        network_name:
            full: Open5GS
        amf_name: open5gs-amf 
        time:
          t3512:
            value: 540