apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pcf-config
  labels:
    epc-mode: pcf
data:
  pcf.yaml: |
    db_uri: mongodb://{{ .Release.Name }}-mongodb-svc/open5gs
    global:
      max:
        ue: 1024  
    logger:
     file:
       path: /var/log/open5gs/pcf.log
        #level: debug
    pcf:
      sbi:
        server:
        - address: 0.0.0.0
          advertise: pcf-svc
        client:
          scp:
          - uri: http://scp-svc