apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-udr-config
  labels:
    epc-mode: udr
data:
  udr.yaml: |
    db_uri: mongodb://{{ .Release.Name }}-mongodb-svc/open5gs
    global:
      max:
        ue: 1024  
    logger:
     file:
       path: /var/log/open5gs/udr.log
        #level: debug
    udr:
      sbi:
        server:
        - address: 0.0.0.0
          advertise: udr-svc
        client:
          scp:
          - uri: http://scp-svc