apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ausf-config
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |
    global:
      max:
        ue: 1024  
    logger:
     file:
       path: /var/log/open5gs/ausf.log
        #level: debug
    ausf:
      sbi:
        server:
        - address: 0.0.0.0
          advertise: ausf-svc
        client:
          scp:
          - uri: http://scp-svc