apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-udm-config
  labels:
    epc-mode: udm
data:
  udm.yaml: |
    global:
      max:
        ue: 1024  
    logger:
     file:
       path: /var/log/open5gs/udm.log
        #level: debug
    udm:
      sbi:
        server:
        - address: 0.0.0.0
          advertise: udm-svc
        client:
          scp:
          - uri: http://scp-svc