apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ueransim-ue
  labels:
    app: ueransim-ue
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ueransim-ue
  template:
    metadata:
      annotations:
         k8s.v1.cni.cncf.io/networks: >-
          [            
            { "name": "{{ .Release.Name }}-ue-n2-nad" }
          ]    
      labels:
        mode: simulator
        app: ueransim-ue
    spec:
      serviceAccountName: {{ .Release.Name }}-k8s-wait-for
      initContainers:    
      - name: wait-for-gnb
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lapp=ueransim-gnb"                  
      containers:
      - name: ueransim-ue
        image: "{{ .Values.ueransim.repository }}:{{ .Values.ueransim.tag }}"
        imagePullPolicy: {{ .Values.ueransim.pullPolicy }}        
        command: ["/bin/sh", "-c"]
        args:
        - ./nr-ue -c open5gs-ue.yaml;
        securityContext:
          privileged: true        
        volumeMounts:
        - name: ueransim-ue-config
          mountPath: /UERANSIM/build/open5gs-ue.yaml
          subPath: open5gs-ue.yaml
      volumes:
        - name: ueransim-ue-config
          configMap:
            name: ueransim-config